import { randomBytes } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";

export const root = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");

export function coston2DeploymentPath() {
  return resolve(
    root,
    "deployments",
    process.env.QUIETLINE_DEPLOYMENT_FILE ?? "coston2-v2.json",
  );
}

export function parseEnv(path) {
  if (!existsSync(path)) return {};
  return Object.fromEntries(
    readFileSync(path, "utf8")
      .split(/\r?\n/u)
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith("#") && line.includes("="))
      .map((line) => {
        const separator = line.indexOf("=");
        return [line.slice(0, separator), line.slice(separator + 1)];
      }),
  );
}

export function writeEnv(path, values, heading) {
  mkdirSync(dirname(path), { recursive: true });
  const lines = [
    `# ${heading}`,
    "# Generated by pnpm coston2:prepare. Do not commit this file.",
    ...Object.entries(values).map(([name, value]) => `${name}=${value}`),
    "",
  ];
  writeFileSync(path, lines.join("\n"), { encoding: "utf8", mode: 0o600 });
}

export function secret(bytes = 32) {
  return randomBytes(bytes).toString("hex");
}

export function isPlaceholder(value) {
  return !value || /^(?:REPLACE_|DERIVED_|PENDING_|https:\/\/YOUR_|0x0{40}$)/u.test(value);
}

export function requireValue(values, name, pattern) {
  const value = values[name]?.trim();
  if (isPlaceholder(value)) throw new Error(`${name} is not configured`);
  if (pattern && !pattern.test(value)) throw new Error(`${name} has an invalid format`);
  return value;
}

export function run(command, args, options = {}) {
  const isWindowsCorepack = process.platform === "win32" && command === "corepack";
  const executable = isWindowsCorepack ? process.execPath : command;
  const commandArgs = isWindowsCorepack
    ? [
        resolve(
          dirname(process.execPath),
          "node_modules",
          "corepack",
          "dist",
          "corepack.js",
        ),
        ...args,
      ]
    : args;
  const result = spawnSync(executable, commandArgs, {
    cwd: options.cwd ?? root,
    env: { ...process.env, ...options.env },
    encoding: "utf8",
    stdio: options.capture ? "pipe" : "inherit",
    shell: false,
  });
  if (result.error) throw result.error;
  if (result.status !== 0) {
    if (options.capture) {
      process.stderr.write(result.stdout ?? "");
      process.stderr.write(result.stderr ?? "");
    }
    throw new Error(`${command} exited with status ${result.status}`);
  }
  return result.stdout ?? "";
}

export function readJson(path) {
  return JSON.parse(readFileSync(path, "utf8"));
}

export function writeJson(path, value) {
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`, "utf8");
}
